# Generated by Django 6.0.2 on 2026-02-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_task_task_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='payout',
            new_name='cost_per_action',
        ),
        migrations.AddField(
            model_name='task',
            name='worker_reward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
